spring:
  datasource:
    url: jdbc:mysql://mysql:3306/skillbridge_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:skillbridge_user}
    password: ${DB_PASSWORD:skillbridge_password}
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    
logging:
  level:
    com.skillbridge: INFO
    org.springframework: WARN