spring:
  application:
    name: skillbridge-backend
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:mysql://localhost:3306/skillbridge_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: skillbridge_user
    password: skillbridge_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
  security:
    user:
      name: admin
      password: admin123
      
server:
  port: 8080
  servlet:
    context-path: /api
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.skillbridge: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE